version: '3.8'

services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    volumes:
      - victoriametrics_data:/storage
    ports:
      - "8428:8428"
    networks:
      - monitoring

  vmagent:
    image: victoriametrics/vmagent:latest
    container_name: vmagent
    volumes:
      - ./vmagent:/etc/vmagent/
    command:
      - '-remoteWrite.url=http://victoriametrics:8428/api/v1/write'
      - '-promscrape.config=/etc/vmagent/vmagent.yml'
    depends_on:
      - victoriametrics
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_INSTALL_PLUGINS=victoriametrics-metrics-datasource
    ports:
      - "3000:3000"
    depends_on:
      - vmagent
      - victoriametrics
    networks:
      - monitoring

volumes:
  victoriametrics_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge

