version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - victoriametrics
    networks:
      - monitoring

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    volumes:
      - victoriametrics_data:/storage
    ports:
      - "8428:8428"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      # - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - victoriametrics
    networks:
      - monitoring

volumes:
  victoriametrics_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge

